## Homepage deployment

[[deployment]]
name = "homepage"
description = "Application dashboard"
tags = ["core"]
deploy = true

[deployment.config]
server = "Roach"
image.type = "Image"
image.params.image = "ghcr.io/gethomepage/homepage:latest"
restart = "unless-stopped"
network = "core"
environment = """
HOMEPAGE_ALLOWED_HOSTS=[[DOMAIN]]
PUID=[[SERVICE_UID]]
PGID=[[SERVICE_GID]]
"""
volumes = """
[[HOST_APPDATA]]/homepage/config = /app/config
[[HOST_APPDATA]]/homepage/images = /app/public/images
"""
labels = """
traefik.enable = true
traefik.http.routers.homepage.rule = 'Host(`[[DOMAIN]]`)'
traefik.http.routers.homepage.tls.certresolver = cloudflare
traefik.http.routers.homepage.middlewares = authentik@file
traefik.http.services.homepage.loadbalancer.server.port = 3000
"""

## Speedtest Tracker deployment

[[deployment]]
name = "speedtest-tracker"

[deployment.config]
server = "Roach"
image.type = "Image"
image.params.image = "lscr.io/linuxserver/speedtest-tracker:latest"
poll_for_updates = true
network = "core"
restart = "unless-stopped"
environment = """
PUID = [[SERVICE_UID]]
PGID = [[SERVICE_GID]]
APP_KEY = [[STT_APP_KEY]]
DB_CONNECTION = pgsql
DB_HOST = [[STT_DB_HOST]]
DB_PORT = 5432
DB_DATABASE = speedtest_tracker
DB_USERNAME = speedtest_tracker
DB_PASSWORD = [[STT_DB_PASSWORD]]
DISPLAY_TIMEZONE = [[SYSTEM_TZ]]
SPEEDTEST_SCHEDULE = "0 5 * * *"
SPEEDTEST_SERVERS = "5935"
"""
volumes = """
[[HOST_APPDATA]]/speedtest-tracker = /config
"""
labels = """
traefik.enable = true
traefik.http.routers.speedtest-tracker.rule = 'Host(`speedtest.[[DOMAIN]]`)'
traefik.http.routers.speedtest-tracker.tls.certresolver = cloudflare
traefik.http.services.speedtest-tracker.loadbalancer.server.port = 80
homepage.group = Core
homepage.name = Speedtest Tracker
homepage.description = Internet speed logging and monitoring
homepage.icon = speedtest-tracker
homepage.href = https://speedtest.[[DOMAIN]]
homepage.widget.type = speedtest
homepage.widget.url = http://speedtest-tracker
homepage.widget.version = 2
homepage.widget.key = [[STT_API_TOKEN]]
homepage.widget.bitratePrecision = 2
"""
