name: monitoring

services:
  # Prometheus metrics server
  prometheus:
    image: docker.io/prom/prometheus:v3.6.0
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.retention.time=7d
      - --storage.tsdb.retention.size=2GB
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    networks:
      - default
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN}`)
      - traefik.http.routers.prometheus.tls.certresolver=cloudflare
      - traefik.http.services.prometheus.loadbalancer.server.port=9090

volumes:
  prometheus-data:
    driver: local

networks:
  default:
    name: monitoring
    driver: bridge
  backend:
    external: true
