name: monitoring

services:
  # Prometheus metrics server
  prometheus:
    image: docker.io/prom/prometheus:v3.6.0
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.retention.time=7d
      - --storage.tsdb.retention.size=2GB
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ${HOST_APPDATA}/prometheus:/prometheus
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN}`)
      - traefik.http.routers.prometheus.tls.certresolver=cloudflare
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
