name: immich

services:
  # Postgres database with vector support
  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - database-data:/var/lib/postgresql/data

  # Redis compatible cache
  cache:
    image: valkey/valkey:8
    container_name: immich-cache
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - cache-data:/data

  # Immich server
  server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich-server
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - DB_HOSTNAME=immich-database
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE_NAME=${POSTGRES_DB}
      - REDIS_HOSTNAME=immich-cache
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - server-data:/data
    networks:
      - default
      - core
    depends_on:
      - database
      - cache
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`immich.${DOMAIN}`)
      - traefik.http.routers.immich.tls.certresolver=cloudflare
      - traefik.docker.network=core
      - homepage.group=Media
      - homepage.name=Immich
      - homepage.description=Photo and video library
      - homepage.icon=immich
      - homepage.href=https://immich.${DOMAIN}
      - homepage.widget.type=immich
      - homepage.widget.version=2
      - homepage.widget.url=http://immich-server:2283
      - homepage.widget.key=${WIDGET_API_KEY}

  # Immich machine learning service
  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich-machine-learning
    restart: unless-stopped
    volumes:
      - model-cache:/cache

networks:
  default:
    name: immich
    driver: bridge
  core:
    external: true

volumes:
  database-data:
    driver: local
  server-data:
    name: immich-server-data
  model-cache:
    driver: local
  cache-data:
    name: immich-cache-data
